// les URLs utilisées dans l'application
// Call API
export const apiAtmoSud = {
    urlBase: http://monUrlApi,
    urlCapteursSites: '/observations/capteurs/sites',
    urlCapteursMesures: '/observations/capteurs/mesures',
    urlCapteursMesuresDernieres: '/observations/capteurs/mesures/dernieres',
    urlCapteursMesuresHistoriques: '/observations/capteurs/mesures/historique',
    urlStations: '/observations/stations',
    urlStationsMesuresDerniere: '/observations/stations/mesures/derniere',
    urlStationsMesures: '/observations/stations/mesures',
    urlTaxonomyStation: '/jsonapi/taxonomy_term/station',
};
export const apiAirCarto = {
    urlBase: http://monUrlApi,
    urlCapteursMetadata: '/capteurs/metadata',
    urlCapteursData: '/capteurs/dataNebuleAir',
};
export const API_KEYS = {
    purpleAir: 'maCleApiPurpleAir',
};